### ISSUE TITLE
Single ics file

### ISSUE THREAD

**Issue by avidseeker** [pimutils/khal#1234]
Whenever a new event is created or imported, khal creates a whole new ics file just for that event.

Typical calendar services combine all calendar events into one ics file. E.g: schedule.ics, work.ics, academic.ics, and so on...

It would be more cleaner if khal can combine events into a single ics file and keeps it updated.

**Comment by d7415** [comment]
Much as with `khard`, this is not the design of `khal`, and that is clearly stated in the docs (it's the first item on the [features list](https://github.com/pimutils/khal#features)). You can read more detail about the `vdir` format [here](https://vdirsyncer.readthedocs.io/en/stable/vdir.html).

One event per file is also, in my opinion, much cleaner than one massive combined file.

**Comment by WhyNotHugo** [comment]
This is by design. Having multiple events per file makes writing files really complicated and prone to race conditions across processes modifying different events (eg: a background sync while you edit some event).

Khal stores files in a vdir; a directory where each event is a separate file. This convention is compatible with vdirsyncer if you need to sync with other services via CalDAV or alike.

What can of interaction are you trying to achieve with that doesn't work with this?

**Comment by avidseeker** [comment]
> much cleaner than one massive combined file.

But file names are UID, and are not sorted in chronological order. How do you know where your last event file is?

> race conditions

That's not a problem since these are already managed by the syncing service. For example Syncthing would detect if there's edit conflict. In the end, this is up to the user to take care of. All Khal should care about is parsing ics.

I want a single ics file to be synced via syncthing to my phone, and read by ICSx5 to a local calendar.

**Comment by avidseeker** [comment]
Related: [When do I need Vdirsync](https://vdirsyncer.pimutils.org/en/stable/when.html?highlight=syncthing#why-not-file-sync-dropbox-git-vdir)

> if it comes to a sync conflict, most sync services are not daring to merge files

> Such a setup doesn’t work at all with smartphones. Vdirsyncer, on the other hand, synchronizes with CardDAV/CalDAV servers

**Comment by WhyNotHugo** [comment]
> But file names are UID, and are not sorted in chronological order. How do you know where your last event file is?

You need to parse the events in order to find the last one. Keeping them in the same ics file also requires that you parse all of them to find the last one.

I'm not sure there is any way to reflect the chronological order in filenames, since a recurring event may happen both before and after another event.

The only way to avoid parsing all of them is to keep an index/cache.

> That's not a problem since these are already managed by the syncing service. For example Syncthing would detect if there's edit conflict. In the end, this is up to the user to take care of.

So as soon as you edit two different events in different files, you fall into manual conflict-resolution mode? This is exactly the kind of issue that's being avoided.

Syncthing is an unusual example too: it syncronises files without caring about content. Usually the focus is on synchronizing via CalDav to a server where other applications (including mobile ones) can syncronise too.

> All Khal should care about is parsing ics.

This is exactly what khal does. It's just that the choice was made of one-file-per-event instead of one-file-per-calendar. Both alternatives have their upsides and downsides.

Writing is a lot easier for the first case. Reading is slightly easier for the second case. This is basically like comparing maildir vs mbox.

**Comment by avidseeker** [comment]
Ok, I see now the point of having separate files, and I see how important it is to have atomic writes in vdir. But let me show the use of "one file per calendar".

> Syncthing is an unusual example

My goal is to sync calendars between PC and phone without server. Using Syncthing and ICSx5 Fdroid app, I keep a single `calendar.ics` file with all events. Any changes from the phone reflect in `calendar.ics` to PC. Now I'm trying to change `calendar.ics` from PC to have these changes reflect on phone.
