### ISSUE TITLE
icalendar>=3.9.2 required for testsuite

### ISSUE THREAD

**Issue by untitaker** [pimutils/khal#406]
There's this test in `tests/backend_test.py` that uses `__version__`, which was only introduced in `icalendar==3.9.2``(https://github.com/collective/icalendar/commit/86e4106a3b7a6ec9d602084e40d33eb4f78c9c70#diff-4913494b4cdb8751d12e71febe0a243c) to check for versions older than 3.9.2.

Several options:

* Fix the test to use `pkg_resources` such that it actually works with older versions
* Just drop support for older icalendar versions

**Comment by untitaker** [comment]
cc @lfam

**Comment by untitaker** [comment]
@geier I can prepare a PR if you tell me which option you prefer.

**Comment by lfam** [comment]
I'd prefer to be able to use older versions of icalendar.

This is because the current version of icalendar (3.9.2) does not work with the 2.5.x series of dateutil (https://github.com/collective/icalendar/issues/194), but there are many fixed bugs in the 2.5.x series of dateutil. So, I'd rather not go backwards with dateutil.

On the other hand, if you can get icalendar to release with your fix for that issue, then your second option would work for me.

**Comment by geier** [comment]
While I do dislike the use of `pkg_resources` (for no good reasons at all) I think this is the way we should go, especially if icalendar 3.9.2 does not work with the latest dateutil.
