### ISSUE TITLE
Use gnu parse_datetime for entering dates/times

### ISSUE THREAD

**Issue by bernhardbrunner** [pimutils/khal#442]
parse_datetime is part of the gnu library and allows entering date specifications in natural language, e.g. next monday. 
Some examples of the possibilities can be found here: http://www.cyberciti.biz/tips/linux-unix-get-yesterdays-tomorrows-date.html
Notes: 
- there seems to be a python module called parsedatetime, but it seems to be a reimplementation of the original function parse_datetime, which is part of the gnu library
- there seems to have been a bufferoverflow in parse_datetime, so maybe look out for the patched version before integrating it

**Comment by geier** [comment]
Hi and thank you for that suggestion.

I don't think integrating GPL software is an option for us, because I believe it is against the spirit of the GPL of using them in python in non-GPL software.

Regarding the parsedatetime library: the problem is, it doesn't tell which of part of a string matches, so it couldn't be (easily) used everywhere we parse datetimes. If someone makes a proof-of-concept, I'm happy to have a look at it.

**Comment by geier** [comment]
also I'm closing this as a duplicate of #169.
