### ISSUE TITLE
New Daycolumn Discussion

### ISSUE THREAD

**Issue by geier** [pimutils/khal#463]
Current suggestions:
- skip dayheaders when scrolling in the right column
- page "flipping" when scrolling (down) in the right column (remove  `khal/ui/__init__.py L 211` )
-  make old behavior configurable
- skip days with no events alltogether

**Comment by untitaker** [comment]
I'd vote against `#3` and rather wait until somebody actually complains.

**Comment by geier** [comment]
@untitaker https://github.com/pimutils/khal/commit/d34049f9024124efb6d91fd7275c7ebb49791e50#commitcomment-18371196

**Comment by untitaker** [comment]
I see, I was thinking you want to make smaller things like "skip dayheaders when scrolling" configurable.

**Comment by untitaker** [comment]
My suggestion from IRC: Hide dayheaders when there are no events on that day.

You'll understand if you don't have events for the next two months.

**Comment by josswright** [comment]
Sorry. I just found this -- I was the person that asked for the old behaviour.

My problem is that I have a number of calendars, including a work calendar, some of which are quite populated. My problem isn't that I have a lot of useless day headers, it's that I have a large wall of text showing multiple days with many events when all I want to see are the events for the current day. 

It would be much more convenient to go back to the old behaviour where I just see the currently selected day's events. Is this likely to be possible to implement easily? I'd love to have this back.

**Comment by josswright** [comment]
Just as a follow-up to this -- I  just ran into the problem that events weren't showing up after being added on a day. I eventually found that it's because of the scrolling behaviour when there are too many events on a given day. Would it be possible to have a marker or notification that some events have been hidden?

**Comment by untitaker** [comment]
I also saw this, wanted to report it as bug. Is that intentional?

**Comment by geier** [comment]
I'm not entirely sure what you mean yet: are you surprised that after adding an event you might not see it, because it is listed *after* the ones currently in view?

**Comment by geier** [comment]
and yes, we should perhaps make the bottom row display something like `and 15 more events`.

**Comment by josswright** [comment]
Hi,

Yes, that's exactly what confused me. I added an event, then didn't see it. It was only by chance that I found the scrolling behaviour, because there wasn't a visual indicator.

Is the number of items shown per day configurable? With the calendars I have, nearly every day has a significant number of items hidden. It seems odd behaviour to enforce showing multiple days, with events hidden on each day, rather than showing all events for the selected day!

**Comment by geier** [comment]
Ok, I think I can reproduce that behaviour, haven't seen that before....

**Comment by geier** [comment]
I believe ab7333602092830c982793eba37c1678461e0d8c caused some regression here.
@josswright could you test if 683493cf24a3edfc89c8ba6d1dc8ea9e74da3d5b works somewhat better? (`git checkout 683493cf24a3edfc89c8ba6d1dc8ea9e74da3d5b`)

**Comment by geier** [comment]
The problem could also be event lines that get wrapped.

**Comment by josswright** [comment]
Hmm. I've just loaded up ikhal after an update last night. (Running this through the khal-git package in Arch Linux.) I can't seem to reproduce the behaviour right now. Days seem to be taking as much room as they need, and adding an event is showing up correctly.

**Comment by josswright** [comment]
(I'd still love to have the option to show only the current day's (or current day + n days') events, though! :)

**Comment by josswright** [comment]
Just as another follow-up, I'm still regularly getting events 'hidden' by the scrolling behaviour. After playing around with it a bit, I'm suspecting that it might be due to how much space is made available for each day as you scroll around. 

When I open ikhal, the current day always seems to have enough space for all its events. If I scroll around days, though, it seems that the space available for a day's events can, somehow, become smaller. (Maybe when a day with few events is selected the number is reduced?)

A second issue is that I have "event_view_always_visible = true" set. For a start, this no longer seems to be respected -- the event view seems only to be shown when I've selected an event. Secondly, and more importantly, the event view seems to pop up over the event view when it appears. This means that if I'm scrolling down the event view in ikhal, the cursor will end up 'behind' the event view.

Apologies if I'm not explaining this well. I'm finding it hard to pin down exactly what is causing this set of odd behaviour, and a lot of it seems related to the multi-day changes to the event view column ("daycolumn?"). I suspect that a lot of this might be caused by the window not recalculating its size correctly when things change, like a new day being selected, the event view window popping up, or the terminal being resized.

None of these problems happened with the old behaviour... :)

A

**Comment by geier** [comment]
@josswright are you saying that the scrolling in days behaviour has been fixed with the recend commit? (I'm guessing you are talking about 08a6863bf100ae483bc9e741ad0e7f47270c1a08). If so, do you have events that (used to) take up more than one line (because of a very long summary)?

I'll have a look at the `event_view_always_visible` issue.

Thanks for checking this, and yes, something like the old behavior will come back, but I can't make any promises on when (but you can keep using the 0.8 branch till then).

**Comment by josswright** [comment]
@geier Yes, it looks like the scrolling behaviour has been fixed at some point in recent commits. I'm afraid that I didn't note what commit I was on before my last update, so I can't track down the exact change that made things work.

Looking at it, though, and given that I get khal through Arch's khal-git package, I believe that it may have been https://github.com/pimutils/khal/commit/80be3bf1a379e15a093d85871afa02c0219886f9 that fixed the issue. (I see some recalculation of canvas sizes there, so it may have accidentally fixed it.) I can't believe that I wasn't running https://github.com/pimutils/khal/commit/08a6863bf100ae483bc9e741ad0e7f47270c1a08 already as I definitely would have run a system-wide update in the past month.

For reference, I think that the `event_view_always_visible` is behaving as expected. It's just visually a bit distracting when the event view window pops in and out of existence as you're scrolling through the list of events!

**Comment by geier** [comment]
I'm going to close this now, please open new issues for any additional ideas, bugs, etc.
