### ISSUE TITLE
Double issue: invalid time range parsing + warning message display

### ISSUE THREAD

**Issue by pdav** [pimutils/khal#666]
Two problems are shown in the attached screenshot:
- when entering this event (using only default values, especially the start and end hours 8:00 to 9:00), the time range is not understood by khal
- warning messages are displayed (very shortly, less than 1 sec) in the middle of the screen, and are erased as soon as the screen is being refreshed, which prevents the user to see them

![screenshot_20170608_082535](https://user-images.githubusercontent.com/412628/26914970-5213000a-4c24-11e7-86a0-877a53979524.png)

**Comment by geier** [comment]
I'll look into it.

**Comment by geier** [comment]
Thank you for reporting this, it turned out it was a quite nasty bug that might lead to a change of the end time when you are editing an event, but not editing the end time but moving the cursor through the end time (the end time would be set to the start time +1h, but on the end date).

I have pushed a fix and released a new version.

@pimutils/packaging please make a new package, thanks! (only khal version >0.9.4 is affected).
also, please ignore the test failures in tests/cli_test.py under python 3.3 (vdirsyncer doesn't support python 3.3 any more).
