### ISSUE TITLE
Development version of khal does not display calendar by default

### ISSUE THREAD

**Issue by pfertyk** [pimutils/khal#702]
On daily basis I'm using khal 0.9.6. When I run `khal` (without any additional arguments) the calendar for the next 3 months is displayed. I am also working on issues with khal `master` branch, version 0.9.7.dev22+g90864f2.d20170805. When I run that `khal`, I get the help message describing all the commands. Is this just a glitch (maybe I installed the development version incorrectly) or is it a conscious decision to remove the default `calendar` command from khal? If the latter, is there an option to set the default command in the config file?

**Comment by geier** [comment]
Yes, this is intentionally.

Turns out, the default command was confusing to new users and old developers alike, at least in it's current form, because it didn't support all of the commands options and parameterss.

Example:
with default_command = calendar `khal -a home DATE` would not work as intended.

We might bring this back if click properly supports it though.

For now, you might want to use set up an alias like `alias kal='khal calendar'`, which should work as before but supports all options.

We probably should make this a FAQ item, this is surely going to come up again.
