### ISSUE TITLE
Change ikhal's color theme through config file

### ISSUE THREAD

**Issue by geier** [pimutils/khal#705]
Colors color theme should be changeable through the color theme.

This should be easily doable by `literal_eval`ing a string and adding it to the selected color theme (as urwid iterates over the palette list and later attributes overwrite earlier ones with the same name).

Proper documentation might be an issue.

**Comment by pizzacoca** [comment]
Hi, 
By proper doc, do you mean by adding infos in  colors.py ?

**Comment by pizzacoca** [comment]
colors.py : something like that ?
dark = [
    # ikhal calendar panel 
        #fixed elements 
    ('header', 'white', 'black'),
    ('footer', 'white', 'black'),
(...)
        #selected elements 
    ('date header focused', 'black', 'white'),
    ('date header selected', 'dark gray', 'light gray'),
(...)
    # ikhal editor panel
    ('edit', 'black', 'white'),
    ('line header', 'black', 'white', 'bold'),
(...)

**Comment by pizzacoca** [comment]
I am Looking for creating a 256colors theme with few variables to change
defbgcolor = 'h0'
defcolor = 'h2'
defcolor2 = 'h11'
colors256 = [
   ('header', '', '', '', defcolor, defbgcolor, ), 
   ('footer', '', '','', defcolor2, defbgcolor, ), 
   (...)
]
I like use 256 color code because urwid & the console's parameters does not impact my choices (I ask for h11 and have it)
Is a 256colors theme looking good for a future pull request ?

For my understood I've made an ascii draw in my color.py
# +header---------------------------------------------------
# |         dayname     date header focused/selected
# |mon                              
# |th         td              date header focused/selected 
# |name          
# |
# +footer-----------------------------------------------------

Is that look good for documentation in that file ?

N.B. I am still searching how does khal's working for 'list', 'list focused' and well, the most part of the others parameters ^^

**Comment by geier** [comment]
fixed with #1279
