### ISSUE TITLE
dynamic_days doesn't work

### ISSUE THREAD

**Issue by ejeandel** [pimutils/khal#709]
The setting dynamic_days = False doesn't seem to work.
I believe the culprit is commit  6ed2e3dc4cd9558285383b7722915fe88df152b6
self.body._autoextend in DListBox.render should only be called when the Walker is a DayWalker, not when it is a StaticDayWalker.

E.

**Comment by geier** [comment]
Thank you very much for reporting this issue and already pinning the cause if the issue! I believe I just fixed this with 31cc59188ec68f5efe039f412b79aa7e96499960, but I'm going to leave it open, because I really want to write some tests for this, especially as it is a feature I don't use myself, but I don't yet know how to.
