### ISSUE TITLE
better vdirsyncer sync

### ISSUE THREAD

**Issue by aleprovencio** [pimutils/khal#749]
Hello, I don't quite get this quote from the configuration manual: Therefore, you might want to execute khal automatically after syncing with vdirsyncer (e.g. via cron).

I'm using the systemd.timer method for auto syncs, and do a manual vdirsyncer sync every time I need it on demand.

Am I missing a better way of keeping things in sync?

**Comment by WhyNotHugo** [comment]
That comment regarding khal isn't actually sync-related.

Khal has an internal cache, were it keeps processed events. Each time you run khal, it reads that, rather than read the entirety of the files each time (it does check if that cache is out of date though).

This comment suggests that you run khal after each vdirsyncer run, so that this cache is kept up-to-date. This just makes khal start faster, but doesn't affect anything other that the startup speed the next time you run it.

I actually have a systemd unit file which does this (I've never though about including it with `khal` itself though):

```$ cat .config/systemd/user/khal.service    
[Unit]
Description=Update khal's cache
Documentation=man:khal(1)
After=vdirsyncer.service
RefuseManualStart=true

[Service]
ExecStart=/usr/bin/khal
Type=oneshot
StandardOutput=null
```

Just create that, and run `systemd --user enable --now khal`, and everything will be done automatically.

**Comment by aleprovencio** [comment]
Got it, thanks @WhyNotHugo.
Apart from that, is it a bad idea to call `vdirsyncer sync` everytime khal makes edits to the calendar?

**Comment by untitaker** [comment]
Nothing wrong with that, no. I do it too.

**Comment by aleprovencio** [comment]
Thanks guys
