### ISSUE TITLE
Config does not see vdirsyncer

### ISSUE THREAD

**Issue by frrobert2** [pimutils/khal#787]
Yes I am running Ubuntu 16.04, vdirsyncer version 0.17.0a2.dev31+g8f2734c.d20180214, and khal version 0.97.7.dev94+ng4fed3c4
I ran config without having vdirsyncer setup and it setups fine and runs fine.  I renamed the old config file so that I could rerun the config tool to setup vdirsyncer with khal. When I rerun khal's config tool I receive the following error "Sorry, cannot import vdirsyncer. Please make sure you have it installed."
I checked and vdirsyncer syncs fine with the server.  
At least for now could you post the configuration information for khal to sync with vdirsyncer so I can manually do the configuration?
Thanks.

**Comment by amandabee** [comment]
I'm a little confused about what you have tried and read already. Are you saying you ran `khal configure` and the error you got was "Sorry, cannot import vdirsyncer. Please make sure you have it installed."? 

`khal` doesn't really "sync" with `vdirsyncer` -- you use `vdirsyncer` to synchronize calendars (and contacts and tasks) between your server and your local machine and then use `khal` to add, edit and view events locally.  

I'm not sure why `khal configure` would fail, but the instructions at <https://lostpackets.de/khal/configure.html> should get you sorted writing a config file manually. I'm also on Ubuntu 16.04, and I created config at `~/.config/khal/config` -- you can view the full text of mine at:

https://gist.github.com/amandabee/6823142b8ba0c40272d374fc133b5ab0#file-khal-conf

If you've tried creating a config manually, can you share it here, and let us know what happens when you try to run `khal` at the command line?

**Comment by frrobert2** [comment]
amandabee,
I was able to manually configure khal and everything is working as it should be.  Thanks.
The issue with khal config still remains
The third question asked by khal config is:
"Should we try to load vdirsyncer's config? [Y/n]:"
If I answered yes the follow message showed
"Sorry, cannot import vdirsyncer. Please make sure you have it installed."
I assume config is trying to set the path to the local calendars that vdirsyncer is already syncing and will use those instead of creating new ones but for what ever reason is looking in the wrong place for  the config file for vdirsyncer.
Kind of a mute point for me at this time but it still seems to be a bug.

**Comment by HNieme** [comment]
I have the same issue and I think this is due to the fact that my calendars are stored to ~/.calendar/ by vdirsyncer, khal looks in ~/.calendars/, so it doesn't find them. 
Manually writing the config solved the problem

Solving above bug should be an easy fix though.

**Comment by rhanneken** [comment]
[Judging from the code](https://github.com/pimutils/khal/blob/v0.10.3/khal/configwizard.py#L132-L138), the error message "Sorry, cannot import vdirsyncer. Please make sure you have it installed" comes up when the code tries to do two Python `import` statements to access code in the `vdirsyncer` package, and it can't find the package.

In my case, I got the error message because I'd installed `khal` and `vdirsyncer` in two separate [virtual environments](https://docs.python.org/3/tutorial/venv.html).

I solved the problem by installing both `khal` and `vdirsyncer` in the same virtual environment. Using [pipx](https://pipxproject.github.io/pipx/), I did

```sh
pipx install --python python3 vdirsyncer
pipx inject --include-binaries vdirsyncer khal
```

Then I made sure `~/.local/bin` was in my shell's path.

**Comment by geier** [comment]
I what @rhanneken mentions' to be the source of the original issue and therefore close this issue.
