### ISSUE TITLE
Khal crashes after external edit

### ISSUE THREAD

**Issue by ign1s-fatuus** [pimutils/khal#827]
I am having an issue where whenever I go make changes via the external edit  option in interactive mode (ikhal) no further input is registered and I have to stop the program forcefully.

**Comment by geier** [comment]
Can you describe the issue a bit more in detail? 

Do you actually close the external application again? Which version of khal and click are you using?

**Comment by ign1s-fatuus** [comment]
I am using version 0.9.10. When I go to edit externally I do so using vim. After exiting vim via `:wq` I find that vim closes and I am returned to the khal interactive interface. The problem is that it doesn't recognize any keyboard input whatsoever (not even "q" to quit). In order to get back to my khalender I have to kill it and run ikhal again. Internal editing seems to work well though, so I'll just continue to use that.

**Comment by supersambo** [comment]
I experience the same issue.
khal v0.9.10
vim 8.1.751

**Comment by choreutes** [comment]
I have also run into the same issue. I'm currently using khal 0.10.1 and neovim 0.4.3 as my editor. However, I did try several different editors (nano, vim) and they all resulted in the same behaviour of khal. So I think that this issue is not caused by any specific editor. Furthermore I have tested the [click method](https://github.com/pimutils/khal/blob/de06c89652510d7538d22fd9e2da2a44bf1a564c/khal/ui/__init__.py#L737) used to start the external editor and as far as I can tell it works as expected.

So my next best guess would be that the restart of the event loop in the following line fails. I have never worked with urwid but quickly glanced over the documentation. To me it seems like they only support starting the loop **once** and stopping it afterwards. I have not found anything about restarting the loop. Is there anyone with a little more experience who knows for a fact that this is possible? Or might this be the cause of the issue?

**Comment by d7415** [comment]
Reproduced. @choreutes was right to suspect `urwid`. Looks like https://github.com/urwid/urwid/issues/285

**Comment by choreutes** [comment]
I did not notice there was an issue for this already. Thanks for pointing that out, @d7415 :) Since the issue in urwid is open for some time now maybe this can be fixed similar to pazz/alot#1191 by stopping and starting the whole loop?

**Comment by d7415** [comment]
> I did not notice there was an issue for this already. Thanks for pointing that out, @d7415 :) Since the issue in urwid is open for some time now maybe this can be fixed similar to [pazz/alot#1191](https://github.com/pazz/alot/issues/1191) by stopping and starting the whole loop?

I had a go at that yesterday without much success. Depending on the exact steps it either kept crashing or raised `ValueError: something is wrong`. I think my best luck was removing the `stop()` and `start()` lines entirely. I'm cleaning that up and wondering what else I'm missing.

**Comment by d7415** [comment]
#928 should fix this if you want to give it a go. I'm aiming to merge it to master tomorrow.
