### ISSUE TITLE
Deprecate the --day-format option

### ISSUE THREAD

**Issue by ciminobo** [pimutils/khal#936]
This was on khal version 0.9.10 installed on Ubuntu 20.04.

Consider this a suggestion, but I would argue that khal should be as flexible as possible when parsing dates. The --day-format option isn't useful.

khal appeared unable to display an event that I added for the next week. I attempted this command on the date of submitting this issue (which was a Friday).

```
user@user-desktop:~$ khal new "wednesday 1200" 1h "dentist"
user@user-desktop:~$ khal at wednesday 1200
critical: Please supply a datetime, not a date.
user@user-desktop:~$ khal at "05-20-2020" "1200"
critical: Invalid value of `05-20-2020 1200` for a datetime
user@user-desktop:~$ khal at 05-20-2020 12:00
critical: Invalid value of `05-20-2020 12:00` for a datetime
user@user-desktop:~$ khal at 05/20/2020 
critical: Please supply a datetime, not a date.

# this one worked
user@user-desktop:~$ khal at 05/20/2020 00:00
05/20/2020 00:00
1200 1h dentist

# so did this
user@user-desktop:~$ khal at --day-format name wednesday 00:00
name
1200 1h dentist
```
I don't like how I have to 1) tell khal what date format to expect or 2) specify a time along with my date. I would think that, at a minimum, khal should try to parse dates in some order of precedence and the first success should be the format used for that run. If a time isn't specified, then the time should default to 00:00 on the day.

**Comment by d7415** [comment]
Hi. Sorry it's taken so long to reply.

From output on my system it looks like the current version has a more informative error message, but there are a few points here:
- khal expects dates in a specific format (see `khal printformats`) which will be why your "05-20-2020" attempts failed.
- `khal at` is specifically for events happening at a given time - You may prefer e.g. `khal list 05/20/2020 1d` or `khal list wednesday 1d`. The "1d" can be set as a default value with `timedelta = 1d` in the `[default]` section of khal's configuration.
- Your creation seems to have failed, creating an event on Wednesday at 00:00 with a summary of "1200 1h dentist". This is again due to formats. `khal new wednesday 12:00 1h dentist` should work.

I'm going to close this, as the reasoning for the suggestion appears to be invalid.
